CREATE TABLE IF NOT EXISTS client (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS manager (
    no BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);