CREATE TABLE IF NOT EXISTS clients (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS managers (
    no BIGSERIAL PRIMARY KEY,
    label VARCHAR(255) NOT NULL,
    param1 VARCHAR(255)
);